### ISSUE TITLE
Unable to add current Wi-Fi as trusted on iOS 13

### ISSUE THREAD

**Issue by thefsfempire** [passepartoutvpn/passepartout-ios#100]
I encountered this with the latest 1.8.0 release in the App Store and it appears to be affected by a change in iOS 13.

**Affected:**

* iPhone XR - iOS 13.1 DB3
* iPad 6th Gen (Cellular) - iOS 13.1 DB3
* iPad 6th Gen (Wi-Fi) - iOS 13.1 DB3

**Not Affected:**

* iPad 6th Gen (Wi-Fi) - iOS 12.4.1

**To Reproduce:**

1. Install *Passepartout*
2. Import OVPN from Mail/Files
3. On the VPN Host page under *Trusted Networks* it shows *Cellular Network* and *Add current Wi-Fi*
   1. Make sure you're connected to Wi-Fi at this point to continue
4. Tap *Add current Wi-Fi*
5. **\[Bug 1\]** \- Under Cellular Network, a general *Wi-Fi* toggle appears.
6. **\[Bug 2\]** \- Tap *Add current Wi-Fi* again, nothing happens
7. Toggle *Enabled* at the top under VPN
   1. Go through the process of adding the VPN config to the system
8. **\[Bug 3?\]** \- Wi-Fi appears to turn off (icon disappears at least; could be an iOS bug)
9. Under Trusted Networks tap *Add current Wi-Fi* again
10. Your Wi-Fi network will show up here now (disabled by default)
11. Enable this Wi-Fi network as trusted

**Comment by williamg97** [comment]
Getting the same. Although seems to be slightly different error in iOS 13.1. I get "You are not connect to any WiFi network" when trying to add current wifi as a trusted network. Have tried it on multiple wifi's and get the same.

**Comment by keeshux** [comment]
> Getting the same. Although seems to be slightly different error in iOS 13.1. I get "You are not connect to any WiFi network" when trying to add current wifi as a trusted network. Have tried it on multiple wifi's and get the same.

Same here. It's the consequence of getting a nil Wi-Fi SSID. Connect to the VPN first, then you should be able to add it to trusted networks.

By the way, it seems that the "long-term solution" is getting location access privilege. I expect to fix it in the very next release.
