### ISSUE TITLE
IOS13 Shortcuts

### ISSUE THREAD

**Issue by fizzyade** [passepartoutvpn/passepartout-ios#102]
I had some shortcuts that I created, I accidentally deleted one of them and I can no longer add them back.  When I go into the shortcut app Passepartout is not listed in the apps.

**Comment by keeshux** [comment]
Are you able to re-create the shortcut from within Passepartout instead?

**Comment by fizzyade** [comment]
Ahh! Yes, that did the trick.  Seems obvious now, I assumed that it had predefined ones for connections, but you create them and then you can use them.
