### ISSUE TITLE
Comma instead of dot when entering ip addresses

### ISSUE THREAD

**Issue by moneytoo** [passepartoutvpn/passepartout-ios#103]
I have the current version from App Store. I'm unable to enter "." when entering ip addresses (like when overriding DNS for example) because there's none on the opened keyboard (only ",").

![IMG_0151](https://user-images.githubusercontent.com/1071643/66473221-1bd9eb00-ea8f-11e9-9fcf-db0df0c9e873.PNG)

Maybe because of my locale that uses comma as decimal separator.

![IMG_0152](https://user-images.githubusercontent.com/1071643/66473257-2c8a6100-ea8f-11e9-863a-60f0f65d15d1.PNG)

(BTW copy pasting dots from other inputs works around this issue).

**Comment by keeshux** [comment]
Yep, it must be the locale! Will fix in next version.
