### ISSUE TITLE
Unable to connect openVPN with iPhone XR (iOS 13)

### ISSUE THREAD

**Issue by eiGelbGeek** [passepartoutvpn/passepartout-ios#104]
I Think the Screenshot explain the Problem.

Connect ... Allow ... and than a strange UI coming up.

![IMG_3984](https://user-images.githubusercontent.com/26887967/66881468-32b89a00-efc7-11e9-9a65-822a4cc12f65.PNG)
![IMG_3985](https://user-images.githubusercontent.com/26887967/66881473-34825d80-efc7-11e9-9026-69c75504bae2.PNG)

**Comment by keeshux** [comment]
Not an app bug, must be the umpteenth iOS 13 nonsense. Better post a video.
