### ISSUE TITLE
iOS <13 crashes when selecting "Debug log" (Xcode 11.2 bug)

### ISSUE THREAD

**Issue by fkooman** [passepartoutvpn/passepartout-ios#108]
Passepartout 1.9.0 (2125) iOS.

The app just disappears when clicking "Debug log".

**Comment by keeshux** [comment]
Not the case for me. More details?

**Comment by fkooman** [comment]
* iOS 12.4.3 (iPhone 6)
* Connecting to vpn.tuxed.net
  * I mailed you a configuration file you can use to test, if you have time

**Comment by keeshux** [comment]
No crashes on iOS 13. Should test iOS 12 maybe.

**Comment by keeshux** [comment]
@fkooman can you grab a video?

**Comment by fkooman** [comment]
Yes. See your mail for link.

**Comment by keeshux** [comment]
Does it crash when disconnected?

**Comment by fkooman** [comment]
Yes, also. Let me dust off my MBP :)

**Comment by fkooman** [comment]
![image](https://user-images.githubusercontent.com/616885/68088964-84d13a80-fe64-11e9-83ef-b38c61c4752b.png)

**Comment by fkooman** [comment]
those are the only 4 that appear when clicking the "Debug log" button in the iOS app.

**Comment by keeshux** [comment]
Try dropping all filters, just search "Passepartout" text.

**Comment by fkooman** [comment]
```
*** Terminating app due to uncaught exception 'NSInvalidUnarchiveOperationException', reason: 'Could not instantiate class named _UITextLayoutView because no class named _UITextLayoutView was found; the class needs to be defined in source code or linked in from a library (ensure the class is part of the correct target)'
*** First throw call stack:
(0x207c33180 0x206e0b9f8 0x207b3d3a0 0x2122d2de8 0x2122d316c 0x212272304 0x23488ae70 0x2348392e8 0x234742d6c 0x2122d2f28 0x212272304 0x2340de508 0x2122d2f28 0x2122d316c 0x212272304 0x2340dbdf0 0x233e7726c 0x233e77c14 0x233e77ed8 0x233e78628 0x233dd5724 0x233de9714 0x233deab3c 0x233dcdd4c 0x2348b9170 0x20c170c60 0x20c175c08 0x20c0d83e4 0x20c106620 0x234448ad8 0x207bc44fc 0x207bbf224 0x207bbf7a0 0x207bbefb4 0x209dc079c 0x234421c38 0x1013158b0 0x2076828e0)
```

**Comment by keeshux** [comment]
Can you FUCKING believe it? Really FUCKING believe it?

https://stackoverflow.com/questions/58657087/after-upgrading-to-xcode-11-2-from-xcode-11-1-app-crashes-due-to-uitextlayoutv

**Comment by keeshux** [comment]
Well, for quick reference:

![](https://i.stack.imgur.com/mptit.png)

**Comment by fkooman** [comment]
It seems this is not a problem anymore on iOS 13.2, but it is on iOS 12.

**Comment by keeshux** [comment]
Look, [I posted this yesterday](https://www.reddit.com/r/MacOS/comments/dqishu/catalina_split_volumes_im_getting_really_tired_of/) because I couldn't upgrade Xcode 11.1 to 11.2 due to Catalina dumb bugs. And after the struggle I get a buggier Xcode, which is why this crash happens.

I guess I'll now have to wait for an Xcode patch, as the disk space bugs probably won't let me reinstall Xcode 11.1 at the same time on what's without a doubt the crappiest macOS release (and Apple era) ever.

**Comment by fkooman** [comment]
Ouch. Great stuff! :man_facepalming:. As far as I'm concerned you just leave this bug, it will be fixed eventually by Apple, or everyone will have iOS >= 13.2, whichever happens first :stuck_out_tongue:

**Comment by keeshux** [comment]
Dunno, it's a stinky red alert. I don't think I'll release a binary built with this version of Xcode.

Thanks for reporting, I would have NEVER known.

**Comment by keeshux** [comment]
Closing for not being an app issue.

**Comment by jeroenleenarts** [comment]
Xcode 11.2.1 GM seed available. Should fix the issue discussed here.

**Comment by keeshux** [comment]
@jeroenleenarts thanks, for now I've downgraded to 11.1 and it should be just fine.
