### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by yonamerketing** [passepartoutvpn/passepartout-ios#110]
The error is:
Could not determine generated file paths for Intent Definition generation: The file “Intents.intentdefinition” couldn’t be opened because there is no such file.
Can someone could help me please ?

**Comment by keeshux** [comment]
Read the README carefully. It’s the submodules missing.

**Comment by yonamerketing** [comment]
Hi

Thank you for your reply
i resolved it and now its working
i don't know why but the first time i did the submodule update it didnt work
thank you for your help
now i was able to open it in my phone and to import my .ovpn file, and i
imported it in the app, but it was not able to connect
Is the application free ?
i did not see how to do in the README,  can you help me ?
thanks you davide

Best Regards
Yona

**Comment by keeshux** [comment]
@yonamerketing you should open a different issue with _detailed_ steps for connectivity problems, "can't connect" is absolutely not enough. Also don't forget to attach a debug log, it's crucial.
