### ISSUE TITLE
Can’t open opvn file on iPhone

### ISSUE THREAD

**Issue by greatpotoo** [passepartoutvpn/passepartout-ios#111]
I’ve been testing the app on both my iPhone and iPad.  On the iPad I could easily import the ovpn file stored on google drive using apple’s files app from inside the passepartoutvpn app when I try to import the exact same file in the exact same way on my iPhone nothing happens.  Any suggestions?

**Comment by greatpotoo** [comment]
‘cause I did not find a “contact us” function in the app and did not see any other place where to post my “issue” other then in the “issues” section.  So instead of posting a useless comment you could point me in the right direction... or tell me that there is a better place to address my issue.  thank you.

**Comment by keeshux** [comment]
> ‘cause I did not find a “contact us” function in the app and did not see any other place where to post my “issue” other then in the “issues” section. So instead of posting a useless comment you could point me in the right direction... or tell me that there is a better place to address my issue. thank you.

Saying that my comment is useless when you don’t even realize that I only told you that for posting in the wrong repository? Seriously?

The reason you don’t see “quick support buttons” is to filter out people like you, who got the app for free and pretend that my response is due, also in a disrespectful manner.

Finally, there’s an opening alert in the app about the subreddit for issues like these, which you didn’t care to read.
