### ISSUE TITLE
Passepartout always sets default route and DNS servers, even if told not to

### ISSUE THREAD

**Issue by apliedes** [passepartoutvpn/passepartout-ios#116]
I only want to access my local 10.8.0.0/24 network through the VPN, but Passepartout always sets default gw to 10.8.0.1, guiding all my traffic through my VPN. It also seems to enforce the fallback DNS servers (1.1.1.1 etc.), tcpdump of 10.8.0.0/24 shows DNS queries to 1.1.1.1.

In my VPN profile, I have set "Default gateway" and "DNS" to "Manual", with IPv[46] disabled under "Default gateway" section, and "DNS" section left empty.

The desired functionality would be to not touch DNS settings at all, and only direct 10.8.0.0/24 through the VPN.

**Comment by keeshux** [comment]
@apliedes could you:

- Connect to the VPN
- Experience the issue
- Enter the debug log screen
- Share it to beta@passepartoutvpn.app

Thanks!

**Comment by apliedes** [comment]
I sent the full log in email. Here are some interesting parts:

`
10:04:57 - Received PUSH_REPLY: "PUSH_REPLY,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.4 255.255.255.0,peer-id 0,cipher AES-256-GCM"
...
10:04:57 - 	IPv4: addr 10.8.0.4 netmask 255.255.255.0 gw 10.8.0.1 routes []
...
10:04:57 - DNS: No servers provided, using fall-back servers: ["1.1.1.1", "1.0.0.1", "2606:4700:4700::1111", "2606:4700:4700::1001"]
`

That is, route-gateway is given by the server, but as routing is set to "manual" and IPv4 "disabled" under routing, Passepartout shouldn't add this route.

**Comment by keeshux** [comment]
Definitely. Give me a few days to fix this, and thanks for the useful report!

**Comment by keeshux** [comment]
@apliedes are you 100% sure that the traffic is going through the VPN? How are you testing that?

The log may be misleading, but as long as you don't see in the log (which you don't):

```
Routing.IPv4/6: Setting default gateway to ...
```

the default gateway will not be set.

**Comment by apliedes** [comment]
I'm seeing a lot of DNS queries to 1.1.1.1 in my 10.8.0.0/24 network. But thinking of it, it could just be Passepartout incorrectly setting DNS, not default gw. I have DNS set to "manual", and the DNS section is empty, but the log says Passepartout falls back to fall-back servers 1.1.1.1 and others. I don't want to use DNS through my VPN at all, in fact, the 10.8.0.0/24 network doesn't even reach a DNS server (it's not routed/NAT'd anywhere).

**Comment by apliedes** [comment]
Also, my phone is unable to access services at 10.8.0.1 (the VPN host). It works through OpenVPN Connect, so I don't think it's a problem at my end.
