### ISSUE TITLE
Auth failed mullvad.. there is a secret password?

### ISSUE THREAD

**Issue by realpandas** [passepartoutvpn/passepartout-ios#121]
I cannot get mullvad to Authenticate? Log is saying bad credentials. I don’t know why there’s an option for password since I don’t need a password to sign in to web portal. Also I’m on ios13.

Any help appreciated.

**Comment by realpandas** [comment]
I figured it out. Closing.

**Comment by keeshux** [comment]
I was about to answer to omit the password. What was the issue?
