### ISSUE TITLE
Please make sure you have the correct access rights and the repository exists.

### ISSUE THREAD

**Issue by ShimshonMarketing66** [passepartoutvpn/passepartout-ios#123]
Hi There,
I just Tried to run the project like the installation doc said and I got an error when I ran the command : git submodule update 
  
"Please make sure you have the correct access rights
and the repository exists" .

Can someone have an issue please 
Thank you.

**Comment by keeshux** [comment]
@ShimshonMarketing66 please pull from `master` and retry.

**Comment by ShimshonMarketing66** [comment]
Hi David. 
still not working after git pull origin master.
Thank you

**Comment by keeshux** [comment]
Post the full commands and output from the terminal.

**Comment by ShimshonMarketing66** [comment]
margariti@Monas-Mac apps % git clone https://github.com/passepartoutvpn/passepartout-ios.git
Cloning into 'passepartout-ios'...
remote: Enumerating objects: 568, done.
remote: Counting objects: 100% (568/568), done.
remote: Compressing objects: 100% (238/238), done.
remote: Total 10021 (delta 380), reused 468 (delta 302), pack-reused 9453
Receiving objects: 100% (10021/10021), 15.72 MiB | 1.11 MiB/s, done.
fatal: unable to open /Users/margariti/Desktop/apps/passepartout-ios/.git/objects/pack/tmp_pack_2AfpJa: No such file or directory
fatal: index-pack failed
margariti@Monas-Mac apps % git clone https://github.com/passepartoutvpn/passepartout-ios.git
Cloning into 'passepartout-ios'...
remote: Enumerating objects: 568, done.
remote: Counting objects: 100% (568/568), done.
remote: Compressing objects: 100% (238/238), done.
remote: Total 10021 (delta 380), reused 468 (delta 302), pack-reused 9453
Receiving objects: 100% (10021/10021), 15.72 MiB | 1.30 MiB/s, done.
Resolving deltas: 100% (6440/6440), done.
margariti@Monas-Mac apps % cd passepartout-ios
margariti@Monas-Mac passepartout-ios % git submodule init
Submodule 'Submodules/API' (https://github.com/passepartoutvpn/api) registered for path 'Submodules/API'
Submodule 'Submodules/Core' (https://github.com/passepartoutvpn/passepartout-core-apple) registered for path 'Submodules/Core'
Submodule 'Submodules/fastlane-ci-templates' (git@github.com:keeshux/fastlane-ci-templates) registered for path 'Submodules/fastlane-ci-templates'
margariti@Monas-Mac passepartout-ios % git submodule update
Cloning into '/Users/margariti/Desktop/apps/passepartout-ios/Submodules/API'...
Cloning into '/Users/margariti/Desktop/apps/passepartout-ios/Submodules/Core'...
Cloning into '/Users/margariti/Desktop/apps/passepartout-ios/Submodules/fastlane-ci-templates'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:keeshux/fastlane-ci-templates' into submodule path '/Users/margariti/Desktop/apps/passepartout-ios/Submodules/fastlane-ci-templates' failed
Failed to clone 'Submodules/fastlane-ci-templates'. Retry scheduled
Cloning into '/Users/margariti/Desktop/apps/passepartout-ios/Submodules/fastlane-ci-templates'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:keeshux/fastlane-ci-templates' into submodule path '/Users/margariti/Desktop/apps/passepartout-ios/Submodules/fastlane-ci-templates' failed
Failed to clone 'Submodules/fastlane-ci-templates' a second time, aborting
margariti@Monas-Mac passepartout-ios %

**Comment by keeshux** [comment]
Ah, you're damn right. Pull again.

**Comment by ShimshonMarketing66** [comment]
Still the same problem bro.
Thank you.


margariti@Monas-Mac passepartout-ios % ls
CHANGELOG.md                    Libraries                       Podfile                         fastlane
CLA.rst                         Passepartout-iOS                Podfile.include                 res
CONTRIBUTING.md                 Passepartout-iOS-Tunnel         Podfile.lock                    scripts
Gemfile                         Passepartout.xcodeproj          README.md                       swiftgen.yml
Gemfile.lock                    Passepartout.xcworkspace        Submodules
LICENSE                         PassepartoutCore-iOS            ci
margariti@Monas-Mac passepartout-ios % git submodule init
margariti@Monas-Mac passepartout-ios % git submodule update
Cloning into '/Users/margariti/Desktop/apps/passepartout-ios/Submodules/fastlane-ci-templates'...

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:keeshux/fastlane-ci-templates' into submodule path '/Users/margariti/Desktop/apps/passepartout-ios/Submodules/fastlane-ci-templates' failed
Failed to clone 'Submodules/fastlane-ci-templates'. Retry scheduled
Cloning into '/Users/margariti/Desktop/apps/passepartout-ios/Submodules/fastlane-ci-templates'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:keeshux/fastlane-ci-templates' into submodule path '/Users/margariti/Desktop/apps/passepartout-ios/Submodules/fastlane-ci-templates' failed
Failed to clone 'Submodules/fastlane-ci-templates' a second time, aborting
margariti@Monas-Mac passepartout-ios % 
margariti@Monas-Mac passepartout-ios %

**Comment by keeshux** [comment]
Delete the directory and redo git clone.
