### ISSUE TITLE
Not works with mobile data

### ISSUE THREAD

**Issue by manveersinghdodiya** [passepartoutvpn/passepartout-ios#125]
I have issue with the mobile data when i connect my ovpn file with wifi network it works fine but when i connect with mobile data, vpn not establish connection.

**Comment by keeshux** [comment]
Post more info or I will close the issue.

**Comment by manveersinghdodiya** [comment]
Some time my ovpn file connect with my server when my device is on mobile network and after 2-3 hours it automatically disconnect and not connect after that even after reinstall tha app but not able to connect again. Then i have to resent iphone network setting then able to connect. But the same file works fine with openvpn official application.

**Comment by keeshux** [comment]
Debug logs required.

**Comment by manveersinghdodiya** [comment]
[debug-20191226-212136.txt](https://github.com/passepartoutvpn/passepartout-ios/files/4002955/debug-20191226-212136.txt)

**Comment by keeshux** [comment]
Okay, duplicate of https://github.com/passepartoutvpn/tunnelkit/issues/145

**Comment by manveersinghdodiya** [comment]
Some times it connects smoothly but some times not then it hangs device internet.
