### ISSUE TITLE
No internet when connecting over wifi

### ISSUE THREAD

**Issue by krimac** [passepartoutvpn/passepartout-ios#126]
Hi, I’m having trouble when connecting to a VPN server over WIFI, using the iOS app (iPhone XSMAX iOS 13.3).
I have no internet and can not reach any other machines on the network. There is no error shown in the app and it seems to have connected correctly. 

The WiFi I’m connecting through is on a different network than the VPN. 
The connection is flawless when done over 4G. 
Is there anything I have to tweak in the app ?

**Comment by keeshux** [comment]
Please provide more information on your local network layout.
