### ISSUE TITLE
Feature request: Restrict network access per app?

### ISSUE THREAD

**Issue by Workings** [passepartoutvpn/passepartout-ios#127]
With the lack of app level firewall on iPhones, would it be possible to limit traffic to user selected apps?
On side note, why is location required for trusted networks? Seems fine when removing from ServiceViewController, or am I missing something?

**Comment by keeshux** [comment]
AFAIK, per-app restriction/selection is not possible on iOS.

The location permission requirement has been introduced in iOS 12 or 13. Without it, access to the SSID of current Wi-Fi is only allowed when connected to the VPN through that Wi-Fi. Maybe also in other scenarios that I honestly can't remember at the moment.
