### ISSUE TITLE
Active profile choice is lost after renaming

### ISSUE THREAD

**Issue by digitalec** [passepartoutvpn/passepartout-ios#128]
#### Steps to reproduce:
- Select VPN host from main screen
- Select _Use this profile_
- Enable connection
- Tap _Edit_ from top right
- Rename connection
- Swipe back to main screen
  - Status shows _Active_ but renamed profile does not show “In use” under hosts
  - Tapping _Status_ does nothing
- Force close app and reopen
  - _Note: Sometimes the app will crash on its own here_
- Status shows _Disabled_ however, system is still connected.
- Select VPN host
- Select _Use this profile_
- Enable connection
  - Status shows _Disconnecting_ then _Inactive_. (It may or may not automatically reconnect.)

_Passepartout 1.10.1 (2263)_
_iOS 13.3_

**Comment by keeshux** [comment]
> * Status shows _Disabled_ however, system is still connected.
> * Select VPN host
> * Select _Use this profile_

@digitalec at this point, going to main screen and back to profile, status correctly shows as "Active" again. Can you confirm this?

**Comment by digitalec** [comment]
Confirmed. If I skip the final step of enabling, going back to the main menu and then back to the profile, it shows “Active”. Status shows disabled but if I do that a second time, going back to the main menu shows Status as Active.

**Comment by keeshux** [comment]
Establishing a connection is not necessary to reproduce the issue, which is actually related to the app losing knowledge of the active profile after renaming it (as per title change).
