### ISSUE TITLE
Split DNS not working?

### ISSUE THREAD

**Issue by mdbraber** [passepartoutvpn/passepartout-ios#130]
I'm using Passepartout 1.10.1 (2263) on iPadOS 13.3. My VPN is pushing out DNS settings with domain.tld as search domain and 172.31.0.1 as (internal) DNS server (this checks out in the Server Settings in Passepartout). 

But hosts under domain.tld are being resolved by the system DNS, rather than the tunnel DNS. Btw, using the "dig" and "host" tools in Blink (shell app on iOS) I can check I can reach and query the specified DNS server without a problem.

Is split DNS supposed to work on iPadOS 13.3?

**Comment by keeshux** [comment]
Please attach debug logs and screenshots to prove what you're saying.

**Comment by mdbraber** [comment]
@keeshux sorry for not responding immediately. Here are the requested debug logs and screenshots. I've also tried this with the same OpenVPN server and config om my iPhone and there it does work, but on iPadOS 13.3 it doesn't. I'm testing with my iPad connect to my iPhone hotspot. The iPhone has 172.20.10.2 as IP address and the OpenVPN has 172.31.0.10/32 with gateway 172.31.0.9/32.

![IMG_0056](https://user-images.githubusercontent.com/1781890/73652149-7a525700-4686-11ea-90f0-84f67a580856.png)
[debug-20200203-130650.txt](https://github.com/passepartoutvpn/passepartout-ios/files/4147770/debug-20200203-130650.txt)

**Comment by mdbraber** [comment]
And here's the host /  dig results from within the Blink terminal app used for testing (also used Safari to try and access the HTTPS website on the specified host, but obviously also doesn't work).

FYI the domain used is a public available domain I own but only use internally. There's are no known records for that domain, other than vpn.domain.tld (but there is an authorative nameserver as you can see). This config works as it should (as split DNS) on iPhone over 4G, but not on iPad connected to my iPhone hotspot + VPN.

![IMG_0058](https://user-images.githubusercontent.com/1781890/73652695-c0f48100-4687-11ea-9606-ba7b2982477a.PNG)

**Comment by mdbraber** [comment]
After some more research it seems that the host and nslookup tools aren't correctly following the split DNS, but the ping results for a split DNS is finding it's way to the correct IP address. Weird but it seems it works that way. After some digging with `host`, `dig` and `nslookup` on macOS, it seems these tools also don't work directly with split DNS on that platform, but ultimately ping and other connections like SSH do work. Maybe this helps someone else who's experiencing the same.
