### ISSUE TITLE
Tap on .ovpn file -> nothing happens

### ISSUE THREAD

**Issue by sundaleek** [passepartoutvpn/passepartout-ios#134]
Hi! I'm trying to add .ovpn file(free server)
How to represent bug?
tap "Add new host" >> tap "Folder button" on top right corner >> Choose .ovpn file(ex. this one https://bit.ly/34IaY42)
Problem: after choosing .ovpn file I'm expect some action(ex. go back to previous screen and run this config. BUT In reality tapping on .ovpn file nothing happens. How to fix it?
Device: Simulator iPhone Pro Max
iOS: 13.3
App version: v1.11.0-b2296

**Comment by keeshux** [comment]
No issue, better double check what you're doing.

https://photos.app.goo.gl/8UvC6ZPfDmzjAnV8A
