### ISSUE TITLE
Problems with Installation

### ISSUE THREAD

**Issue by rommadun** [passepartoutvpn/passepartout-ios#135]
Hello, 
i'm using a Raspberry Pi with "pivpn".
I have Problems getting the app to work. In the original OpenVPN-Client App, i just put the .ovpn in an type in my Password.
Now i have to put in an Account? What do i have to put in there?
I tried nearly everything, just the name of the .ovpn file, just the password, both and nothing...
It wont connect to my server.
Please Help. :-)
Sorry for the bad english :3

**Comment by keeshux** [comment]
This is not a support board.

Please use this: https://www.reddit.com/r/passepartout

**Comment by rommadun** [comment]
> This is not a support board.
> 
> 
> 
> Please use this: https://www.reddit.com/r/passepartout

Sry, i will ask there :)
