### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by 123012013021** [passepartoutvpn/passepartout-ios#138]
I want to program a personal OPENVPN client to connect to my server (centos).
When I run the code on xcode,   the .opvn file imported successful ,but the startup fails, prompting: "Could not reconnect:credentials(details:"keychain.set()"

It trapped me，Thanks for any help。
(xcode version 11.4.1 ,iphone 8 plus)

**Comment by keeshux** [comment]
https://github.com/passepartoutvpn/passepartout-ios#testing

**Comment by 123012013021** [comment]
When I use Passepartout downloaded from the App Store, my .opvpn file can connect to my server. But the passepartout compiled by Xcode is not allowed.
Output:
2020-04-24 17:27:40.983780+0800 Passepartout[4285:1008369] 17:27:40.983 ️ ERROR GracefulVPN.reconnect():83 - Could not reconnect: credentials(details: "keychain.set()")
2020-04-24 17:27:40.994133+0800 Passepartout[4285:1008371] 17:27:40.994&nbsp; DEBUG IntentDispatcher.donateAndLog():316 - Donated <ConnectVPNIntent: 0x28370cb40&gt; {
&nbsp; &nbsp; context = host;
&nbsp; &nbsp; profileTitle = hub-1;
&nbsp; &nbsp; profileId = F655A881-9C80-4BF7-9603-0A5323359F6C;
}


thank you for your help. Fogive your China fans' poor English.


Best wishes.






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Davide De Rosa"<notifications@github.com&gt;; 
发送时间: 2020年4月24日(星期五) 下午5:18
收件人: "passepartoutvpn/passepartout-ios"<passepartout-ios@noreply.github.com&gt;; 
抄送: "不荒。"<326902810@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [passepartoutvpn/passepartout-ios] Connection problem (#138)





 
https://github.com/passepartoutvpn/passepartout-ios#testing

**Comment by keeshux** [comment]
I had understood, and pointed you to the proper documentation. Now take the time to read it, thanks.
