### ISSUE TITLE
Cannot select `.ovpn` file from within app

### ISSUE THREAD

**Issue by fumoboy007** [passepartoutvpn/passepartout-ios#144]
The `.ovpn` file is greyed out when trying to select it in the Passepartout app.

Workaround: Go to the Files app and choose “Copy to Passepartout”.

![IMG_0138](https://user-images.githubusercontent.com/2100868/82946361-0d274200-9f53-11ea-8f62-f1eff1ae1061.png)

**Comment by keeshux** [comment]
I've already been reported the same issue, but I was unable to reproduce it. I don't face the issue on my iPhone.

Please share more details if you find out the culprit.

**Comment by sastraxi** [comment]
I’m hitting this on iPad Pro, 13.5.1.
![D190A00A-04B2-461B-9BB6-4DD9095652A7](https://user-images.githubusercontent.com/898348/85236206-d4f80f80-b3e9-11ea-9722-9504262fdd05.png)

**Comment by sastraxi** [comment]
I’m happy to take some time to help you diagnose btw, let me know what you need!

**Comment by keeshux** [comment]
Hi @sastraxi, could you tell when this regression exactly started? File browsing had worked for almost a year. Thanks!

**Comment by sastraxi** [comment]
Unfortunately, I can't -- I just discovered this app yesterday. I'm using the version from the app store!

**Comment by hanleyhansen** [comment]
Any updates on this? I’m experiencing the same issue on iPad Pro with latest version from the App Store.

**Comment by keeshux** [comment]
Sorry but I'm not experiencing this issue on my two devices:

- iPhone with iOS 13.5.1
- iPad with iOS 13.6 Beta

No way to fix this until someone explains how to replicate it.

**Comment by cameronetchart** [comment]
I have two devices: an iPad Pro running 13.5.1, and importing my profile via the files integration worked perfectly. However, on my iPhone XS running 14.0 public beta, I have the same issue. I just installed the app brand new today. Bug doesn't change depending on what Files provider (dropbox,icloud,etc) I use. So odd that others are experiencing inconsistent results even with these same devices/iOS versions...

The workaround mentioned by OP works though. Just have to tap the config file in Files, it will "open," then hit share sheet, then "more apps" button, then I scrolled down to passepartout and it sent the file over.

**Comment by keeshux** [comment]
iOS betas are always broken, you take the risk.

However, I see that others with non-beta are experiencing this issue on a random basis, so I encourage them to bring up more details.

**Comment by cameronetchart** [comment]
> iOS betas are always broken, you take the risk.
> 
> However, I see that others with non-beta are experiencing this issue on a random basis, so I encourage them to bring up more details.

Oh completely, just wanted to add more data points!

So I just tried to add a second profile on my iPad (13.5.1), where the first profile worked fine. Now, ovpn files in dropbox and iCloud Drive are grayed out when I use the app's file picker. (These files have been tapped so they're cached on the iPad, not just cloud files). However, if I open files.app and copy a file to the "On my iPad" section, then Passepartout allows me to tap it and import. So import works in "On My iPad/Documents", but not in a cloud provider. But I successfully added my first profile on the iPad directly from Dropbox, so that's inconsistent...

**Comment by keeshux** [comment]
> > iOS betas are always broken, you take the risk.
> > However, I see that others with non-beta are experiencing this issue on a random basis, so I encourage them to bring up more details.
> 
> Oh completely, just wanted to add more data points!
> 
> So I just tried to add a second profile on my iPad (13.5.1), where the first profile worked fine. Now, ovpn files in Dropbox and iCloud Drive are grayed out when I use Passepartout's import feature. (These files have been tapped so they're cached on the iPad, not just cloud files). However, if I open files.app and copy a file to the "On my iPad" section, then Passepartout allows me to tap it and import. So import works in "On My iPad/Documents", but not in a cloud provider. But I successfully added my first profile on the iPad directly from Dropbox, so that's inconsistent...

Exactly, same here. Never had a problem personally.

Could go back to an old (obviously unresolved) iOS bug exposing different behavior whether one has another app handling the same file extensions (e.g. OpenVPN Connect). Fact is Passepartout should open any type of file, precisely as a workaround to such bug. This part of app hasn't been changed for almost an year so...
