### ISSUE TITLE
Document browser back button and Done button are not visible

### ISSUE THREAD

**Issue by fumoboy007** [passepartoutvpn/passepartout-ios#145]
Although the buttons are not visible, they are still tappable.

Steps to reproduce:
1. Tap “Add new host”.
2. Tap the folder icon.

![IMG_0138](https://user-images.githubusercontent.com/2100868/82946684-a5bdc200-9f53-11ea-96c7-6484d67411d2.png)

**Comment by keeshux** [comment]
It's an iOS bug (IIRC Light Mode only). They're actually there, if you tap them they will work.

**Comment by fumoboy007** [comment]
I don’t think this is an iOS bug. Looks like the `UINavigationBar` appearance is customized to use a white tint color: https://github.com/passepartoutvpn/passepartout-ios/blob/030385a8f45a647498a75eda2f0f1f0441ecd14a/Passepartout-iOS/Global/Theme.swift#L93.

**Comment by keeshux** [comment]
I'm sure I had commented the whole `applyAppearance` method in the past without luck, but I've now commented that line out and you're actually right.

The damned annoying thing is that I can't override `tintColor` for the picker only, neither with "contained" apperance nor by accessing picker `.navigationController`, which is always nil.

I hate this.

**Comment by keeshux** [comment]
Fixed eventually. Thanks for reminding me this!

**Comment by fumoboy007** [comment]
Yay, thanks for fixing!
