### ISSUE TITLE
High Probability to Get Timeout in UDP

### ISSUE THREAD

**Issue by X-Trafa** [passepartoutvpn/passepartout-ios#146]
High probability of connection timeout in UDP protocol. In the timeout situation, the server can't receive any packages from device.
Platform: iOS
Auth: user-pass

**Comment by keeshux** [comment]
Sounds familiar? https://github.com/passepartoutvpn/tunnelkit/issues/138

**Comment by pengtianabc** [comment]
@keeshux 
### UDP Mode:
1. Server cant receive any udp packet of handshake
2. How could i ensure the vpn thread status?

### TCP Mode:
All OK.

**Comment by keeshux** [comment]
- [x] You discarded the issue template
- [x] You ignored my comments

🤷‍♂️
