### ISSUE TITLE
Error "Missing routing"

### ISSUE THREAD

**Issue by ventsislav-georgiev** [passepartoutvpn/passepartout-ios#150]
I am trying to connect with TAP mode to server in the local network. I get an error message "Missing routing" in the VPN Status field.

Does Passepartout support TAP mode? If not maybe a better error message and a note in the description will be helpful.

> Note: The OpenVPN client does not support TAP mode (See https://openvpn.net/faq/why-doesnt-the-app-support-tap-style-tunnels).

**Comment by keeshux** [comment]
Nope, it doesn’t. I understand that attempting TAP has the effect of not setting up routing (with reason).

**Comment by keeshux** [comment]
In order for me to provide a specific error message, I need to see the (unmasked) logs of your server (OpenVPN) and client (Passepartout) up until the connection is established. This way I could quickly look for some hint at TAP being used, if any exists.

Please send to beta@passepartoutvpn.app
