### ISSUE TITLE
Openssl compilation error(OpenSSL version: 1.1.1g)

### ISSUE THREAD

**Issue by linny006** [passepartoutvpn/passepartout-ios#152]
@keeshux  When I run pod install, it prompts an error to install openssl, the error log is as follows:

pod install
Analyzing dependencies
Pre-downloading: `Convenience` from `https://github.com/keeshux/convenience`, commit `0b09b1e`
Pre-downloading: `TunnelKit` from `https://github.com/passepartoutvpn/tunnelkit`, commit `683617d`
Downloading dependencies
Installing Convenience (0.0.2)
Installing DTFoundation (1.7.14)
Installing Kvitto (1.0.3)
Installing MBProgressHUD (1.2.0)
Installing OpenSSL-Apple (1.1.1g.6)
[!] /bin/bash -c
set -e
./build-libssl.sh --version="1.1.1g" --targets="ios-sim-cross-x86_64 ios64-cross-arm64 macos64-x86_64"
./create-openssl-framework.sh dynamic

Build options
  OpenSSL version: 1.1.1g
  Targets: ios-sim-cross-x86_64 ios64-cross-arm64 macos64-x86_64
  macOS SDK: 10.15
  iOS SDK:
  tvOS SDK:
  watchOS SDK:
  Number of make threads: 4
  Configure options:  no-deprecated
  Build location: /Users/clack/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.1g.6-c9c1b

Downloading openssl-1.1.1g.tar.gz...
Building openssl-1.1.1g for iPhoneSimulator  x86_64...
  Logfile: /Users/clack/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.1g.6-c9c1b/bin/iPhoneSimulator-x86_64.sdk/build-openssl-1.1.1g.log
  Configure...
  Make (using 4 thread(s))...
Problem during make - Please check /Users/clack/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.1g.6-c9c1b/bin/iPhoneSimulator-x86_64.sdk/build-openssl-1.1.1g.log
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: unable to lookup item 'SDKVersion' in SDK 'iphoneos'
xcrun: error: SDK "appletvos" cannot be located
xcrun: error: SDK "appletvos" cannot be located
xcrun: error: unable to lookup item 'SDKVersion' in SDK 'appletvos'
xcrun: error: SDK "watchos" cannot be located
xcrun: error: SDK "watchos" cannot be located
xcrun: error: unable to lookup item 'SDKVersion' in SDK 'watchos'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9571k  100 9571k    0     0   788k      0  0:00:12  0:00:12 --:--:-- 1040k

I checked the log, but I didn't get any useful information. Please help me correct the error, thanks!

**Comment by keeshux** [comment]
You should post the log instead, maybe it is useful.
