### ISSUE TITLE
Restore in-App-Purchase for Family accounts

### ISSUE THREAD

**Issue by PatrickGlatz** [passepartoutvpn/passepartout-ios#158]
Hello, 

I purchased the full version of Passepartout and love it. Since I want my wife also to enjoy the benefits, I downloaded passepartout on her phone using the family download. Now I tried to restore the in-App-purchase for the full version, which normally works for other apps also if it is bought for an other family member, but it is not for Passepartout. Is this a bug or is it not intended (which would be really sad). Thanks in advance 
Patrick

**Comment by keeshux** [comment]
AFAIK, in-app purchases do not apply for Family Sharing. Below is the only (unofficial) article I found about the introduction of Family Sharing also for in-app purchases:

https://www.imore.com/apple-adding-app-purchases-and-subscriptions-family-sharing

There's in fact a mention of it in macOS release notes, just not for iOS. I'll certainly enable the feature as soon as Apple feels like introducing it in iOS, but today I find no such an option in App Store Connect.
