### ISSUE TITLE
Error importing .ovpn file: "The configuration file lacks a required option (cipher)"

### ISSUE THREAD

**Issue by jwcraig** [passepartoutvpn/passepartout-ios#160]
Error encountered in Passepartout 1.12.0 (2394) when adding .ovpn via "Add from Files" on iOS 14.2. My .ovpn file works fine using OpenVPN Connect and Tunnelblick on Catalina. 

The .ovpn file was generated in a kylemanna/openvpn container via:

docker-compose run --rm openvpn easyrsa build-client-full $CLIENTNAME
docker-compose run --rm openvpn ovpn_getclient $CLIENTNAME > $CLIENTNAME.ovpn

**Comment by keeshux** [comment]
Well read the error before posting issues.

**Comment by jwcraig** [comment]
Thanks, I did not realize there was a FAQ as there's no link to it in the repo's README

For anyone else experiencing this, issue resolved by simply adding 'cipher AES-256-GCM' to my .ovpn file. Now able to connect using passepartout on iPhone

**Comment by keeshux** [comment]
> Thanks, I did not realize there was a FAQ as there's no link to it in the repo's README
> 
> For anyone else experiencing this, issue resolved by simply adding 'cipher AES-256-GCM' to my .ovpn file. Now able to connect using passepartout on iPhone

Thanks for the suggestion, I added a direct link to the FAQ right in the README.
