### ISSUE TITLE
Twitch link doesn’t work without Twitch app installed

### ISSUE THREAD

**Issue by akalderon** [passepartoutvpn/passepartout-ios#162]
- Unable to access settings - menu option unresponsive

- Edit button performs no operation

- Twitch link broken with error message

Please issue a fix soon as the app is unusable due to the first two issues listed above

**Comment by akalderon** [comment]
Turns out that the profile data disappeared from the main page even though it is active on the iOS VPN settings.  
Had to recreate profile from scratch.  

Still consider the app broken due to this issue as an end-user.  

Twitch link still broken.

**Comment by keeshux** [comment]
Is the app working again after re-creating profiles? Could you post the Twitch error message?

**Comment by akalderon** [comment]
Yes it seems to work after recreating the profile. 
Screenshot for twitch error attached. ![image](https://user-images.githubusercontent.com/794363/103451706-d9508f80-4c8c-11eb-97e1-b66b5e49f08a.jpeg)
