### ISSUE TITLE
Upgrading to 1.13.0 may lose all profiles

### ISSUE THREAD

**Issue by keeshux** [passepartoutvpn/passepartout-ios#163]
Surely related to JSON parsing.

**Comment by F3000** [comment]
I found a solution: Re-import the .ovpn file 

than it works again

**Comment by keeshux** [comment]
> I found a solution: Re-import the .ovpn file
> 
> than it works again

I know but I still plan to fix it properly. Thank you.

**Comment by F3000** [comment]
Sorry . I can’t reproduce it at the moment 😒
