### ISSUE TITLE
Move OVPN parsing logic to TunnelKit?

### ISSUE THREAD

**Issue by jeroenleenarts** [passepartoutvpn/passepartout-ios#2]
Hi,

Would it be possible to move https://github.com/keeshux/passepartout-ios/blob/master/Passepartout/Sources/VPN/TunnelKitProvider%2BFileConfiguration.swift to tunnel kit?

TunnelKit has an App Store exception. And I would love to be able to use your bit of parsing logic to parse OVPN config format  in the EduVPN app with a bit of code that's available and open for inclusion in an app release.

**Comment by keeshux** [comment]
It's something on my roadmap, but not quite soon. I need to do some refactoring before integrating it the way I want to do it. Current code is based on the `AppExtension` module, I'd like to make it more agnostic.

**Comment by keeshux** [comment]
You might want to review this PR: https://github.com/keeshux/tunnelkit/pull/47
