### ISSUE TITLE
Can I restrict the running of some software to connect via the OpenVPN configured line? 

### ISSUE THREAD

**Issue by FlyBingBingXiaoYuEr123** [passepartoutvpn/passepartout-ios#28]
Excuse me, I want to ask you a question: Can you restrict certain software connections through OpenVPN configured lines in iOS, while other applications do not connect via OpenVPN configured lines?

**Comment by keeshux** [comment]
If it's per-app VPN you're asking -not very clear-, iOS doesn't support it. At least, not in a normal configuration.
