### ISSUE TITLE
Feature request - Support "compress lzo"

### ISSUE THREAD

**Issue by zappe** [passepartoutvpn/passepartout-ios#32]
The VPN provider OVPN.com use "compress lzo" which your app doesn't seem to support?

**Comment by keeshux** [comment]
https://passepartoutvpn.app/faq/#why-is-compression-not-supported

**Comment by keeshux** [comment]
On a second thought: https://github.com/keeshux/tunnelkit/pull/69

I'm afraid this is about `--compress` and not `--comp-lzo`, though.

**Comment by keeshux** [comment]
For future reference, completed in https://github.com/keeshux/tunnelkit/pull/70.
