### ISSUE TITLE
Incorrect VPN status after the profile was renamed

### ISSUE THREAD

**Issue by redpascal** [passepartoutvpn/passepartout-ios#37]
Version: 1.0.3(1323)

When you try to rename "In use" host name that is active, VPN status in UI changes from "Enabled" to "Disabled". In reality, the connection is active and enabled. UI may need some update to reflect the correct status.

**Comment by keeshux** [comment]
Thank you. I'm able to confirm this on any prior version, are you?

**Comment by redpascal** [comment]
I noticed this behavior in 1.0.2 and 1.0.1 as well.

**Comment by keeshux** [comment]
Another side-effect of 3ddfa87.

**Comment by keeshux** [comment]
When this happens, VPN status toggle is also unresponsive.
