### ISSUE TITLE
Enhancement: Support Windscribe (free/premium?) as a network

### ISSUE THREAD

**Issue by rekonnected** [passepartoutvpn/passepartout-ios#39]
Title.

I’m not sure personally if they have an easily accessible API, but if they do then this could likely be made to work. They do have OpenVPN configs for DD-WRT however.
https://windscribe.com/guides/ddwrt

So that could help.

**Comment by Glenta** [comment]
Windscribe support would be really nice

**Comment by keeshux** [comment]
This is in the works, first step being adding LZO compression. There is a licensing issue to be resolved with the author of the library before anything.

**Comment by keeshux** [comment]
@rekonnected also, I would need a test account for the config generator:

> This is a Pro feature. Please login into your Pro account at the top right corner of this page.

**Comment by Glenta** [comment]
> 
> 
> @rekonnected also, I would need a test account for the config generator:
> 
> > This is a Pro feature. Please login into your Pro account at the top right corner of this page.

Ask Garry for a free trial, its only one day though
