### ISSUE TITLE
Encrypted keys in .ovpn

### ISSUE THREAD

**Issue by keeshux** [passepartoutvpn/passepartout-ios#43]
Take encryption passphrase via user input at the time of import.

- [x] [PKCS#1](https://github.com/keeshux/tunnelkit/issues/72)
- [ ] [PKCS#8](https://github.com/keeshux/tunnelkit/issues/80)

**Comment by keeshux** [comment]
Implement via https://github.com/keeshux/tunnelkit/issues/72

**Comment by broizter** [comment]
Tried importing a profile with encrypted key in it and I was never asked for the passphrase. Tested on both 1.2.0 (1511) and 1.2.0 non-beta version. OpenVPN Connect asks for password with the same profile. Let me know if there's any additional information needed!

**Comment by broizter** [comment]
Tried importing a profile with encrypted key in it and I was never asked for the passphrase. Tested on both 1.2.0 (1511) and 1.2.0 non-beta version. OpenVPN Connect asks for password with the same profile. Let me know if there's any additional information needed!

```client
dev tun
proto udp
remote ******.org ****
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
tls-version-min 1.2
verify-x509-name ****** name
cipher AES-128-GCM
auth SHA256
auth-nocache
verb 3
<ca>
-----BEGIN CERTIFICATE-----
***********************************
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
***********************************
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN ENCRYPTED PRIVATE KEY-----
***********************************
-----END ENCRYPTED PRIVATE KEY-----
</key>
<tls-crypt>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
***********************************
-----END OpenVPN Static key V1-----
</tls-crypt>

**Comment by keeshux** [comment]
Ah damn, it's possible. Can you paste the very two lines after `BEGIN ENCRYPTED PRIVATE KEY`? That is, until before the base64 content begins.

**Comment by broizter** [comment]
The base64 content begins immediately after `-----BEGIN ENCRYPTED PRIVATE KEY-----`.

**Comment by keeshux** [comment]
I see, that's because of the key format. Did you generate the key with OpenSSL directly rather than OpenVPN? Because OpenVPN would normally use RSA.

**Comment by keeshux** [comment]
@broizter sorry, I've messed up. :-) Let's keep this issue for both formats.

Did you generate the key with OpenSSL directly rather than OpenVPN? Because OpenVPN would normally use easy-rsa.

**Comment by broizter** [comment]
It was done through [PiVPN](http://www.pivpn.io/). I'm actually unsure what they use to generate the key with.

**Comment by keeshux** [comment]
Should be fixed in the latest beta (1529). Let me know.

**Comment by broizter** [comment]
No luck unfortunately. Still never asked for a passphrase.

**Comment by keeshux** [comment]
Fixed in 1534.
