### ISSUE TITLE
Pushing DOMAIN has no effect

### ISSUE THREAD

**Issue by broizter** [passepartoutvpn/passepartout-ios#48]
Server version: OpenVPN 2.4.0 running on Debian 9.8

Using the option `push "dhcp-option DOMAIN example.com"` on the OpenVPN server has no effect when using Passepartout.  You're still required to use FQDN when accessing a domain. It works without problem when using the OpenVPN Connect app.

This is probably not the right place to ask, but I'd love to join the beta-testing of this app since I'm very interested in the project!

**Comment by keeshux** [comment]
Self reminder: https://developer.apple.com/documentation/networkextension/nednssettings/1406440-domainname

Are you interested in testing or development?

**Comment by broizter** [comment]
I'm interested in testing!

**Comment by keeshux** [comment]
Get in touch via contacts in the footer of https://passepartoutvpn.app/

**Comment by broizter** [comment]
Just wanted to confirm that this does indeed work in the latest beta!
