### ISSUE TITLE
Unable to access App Group container Extension

### ISSUE THREAD

**Issue by techguy19** [passepartoutvpn/passepartout-ios#52]
Hello guys, for any one struggling with this issue, as ricardogalvan23 and I did. 
Besides adding:
- App Groups and Keychain Sharing capabilities
- App IDs with Packet Tunnel entitlements 

you also have to change a few constants in directory: "Passepartout/Sources/GroupConstants.swift"

there you will have to change this constants as they are from passepartout project and will not match your new identifiers:

- public static let teamId = "your team Id" 
- public static let appId = "your app Id" 
- public static let appGroup = "group.your.group.Id" 
- public static let tunnelIdentifier = "com.yourTunnelExtension.bundleIdentifier"

Hopely this helps any one struggling with the same issue. Something so easy made me spend several hours to find the solution.

**Comment by keeshux** [comment]
Thank you, added to README.
