### ISSUE TITLE
Enhancement: support ProtonVPN (free plan) as a network

### ISSUE THREAD

**Issue by pro-sumer** [passepartoutvpn/passepartout-ios#7]
Currently [ProtonVPN](https://protonvpn.com/) has a rather lengthy [OpenVPN Connect](https://itunes.apple.com/us/app/openvpn-connect/id590379981) based [setup](https://protonvpn.com/support/ios-vpn-setup/) for iOS, since they have no native App. This setup can be done in Passepartout (as a "Host") as well. However, it's quite some work and makes the "Host" list longer than needed, as each server will have its own entry.

It would be great if Passepartout could support ProtonVPN as a network instead of a host. Then one would have just a single entry with multiple location/endpoints/presets?

Maybe a small start could be to just support the [5 servers](https://protonvpn.com/vpn-servers) (2x 🇺🇸, 2x 🇳🇱, 1x 🇯🇵) of ProtonVPN's [free plan](https://protonvpn.com/support/how-to-create-free-vpn-account/)?

**Comment by keeshux** [comment]
Sure. However, any new provider network integration is queued until 1.0 is released to the App Store.
