### ISSUE TITLE
Cannot manually connect to a VPN profile

### ISSUE THREAD

**Issue by emericklaw** [passepartoutvpn/passepartout-ios#89]
I cannot connect to other iOS VPN profiles I have setup using the OpenVPN app.

If I try to connect to a profile that is not the Passepartout one it says Connecting... then changes to Not Connected.

If I use the OpenVPN app I can successfully connect.

Even if Passepartout is set to Disabled the iOS VPNs always never connect or what I think is happening is Passepartout is disconnecting it.

**Comment by keeshux** [comment]
Your description is not clear at all. Please be more schematic.

**Comment by emericklaw** [comment]
Sorry, I blame trying to do it on my phone.

I have just tried to replacate and deleted the Passepartout app and the problem still persists.

For now I am going to close this since it appears there is something up with my phone.
