### ISSUE TITLE
Add a feature to go back to default app language (english)

### ISSUE THREAD

**Issue by saxi58** [passepartoutvpn/passepartout-ios#90]
Hi,

I'm an english and french speaker, since my phone is in french the app automatically take the french translated version but it's completely trash, full of typos and words that are not even french (wtf?). Can you please give a way or an option to the app to leave it in english, it's really destroying my eyes. Note that I wanted to correct everything from the french translation but I don't have time for it. Also, switching to english on my phone is not an option.

Thanks

**Comment by keeshux** [comment]
AFAIK it looks like iOS 13 allows apps to override the language from the device settings. If this is the case -I'm not entirely sure yet-, the feature will be implemented soon.

**Comment by keeshux** [comment]
As to the spelling errors, either you provide fixes -everybody HAS TIME to do so- or you'd rather not criticize in such a rude manner. "Trash" is not exactly how you contribute to improving things.

Additionally, translators could not visualize phrases in the app context more than from string identifiers, which can bring all those sorts of weirdnesses.

**Comment by saxi58** [comment]
I didn't mean to be rude, I just don't like half made work. I was really comfortable with the english translation but once that french one came out it was full pain for my eyes. At least typos are ok, anyone can do some even me, but before submitting anything translator need to check at least if their translation are kind of ok with some spell check website. For now the french translation is not correct and I hope someone can take time someday to correct it or I'll do it myself when I'm back home in a month. Once again, didn't mean to be rude and I'm sorry if it was understood like that. Thanks you

**Comment by keeshux** [comment]
You could have invested the time it took to write these comments in screenshots instead, and I'm sure we could have fixed the errors already, even if I'm not a French speaker.
