### ISSUE TITLE
Installing OpenSSL-Apple (1.1.0j.2)  come error

### ISSUE THREAD

**Issue by chuhouyi** [passepartoutvpn/passepartout-ios#92]
When I went to ‘pod install’ according to the test steps, pod made a mistake.

Installing MBProgressHUD (1.1.0)
Installing OpenSSL-Apple (1.1.0j.2)
[!] /bin/bash -c 
set -e
./build-libssl.sh --version=1.1.0j
./create-openssl-framework.sh dynamic

Build options
  OpenSSL version: 1.1.0j
  Targets: ios-sim-cross-x86_64 ios64-cross-arm64 tvos-sim-cross-x86_64 tvos64-cross-arm64 macos64-x86_64
  macOS SDK: 10.14
  iOS SDK: 12.2
  tvOS SDK: 12.1
  Number of make threads: 4
  Configure options:  no-deprecated
  Build location: /Users/houyi/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.0j.2-e88e1

Downloading openssl-1.1.0j.tar.gz...
Building openssl-1.1.0j for iPhoneSimulator 12.2 x86_64...
  Logfile: /Users/houyi/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.0j.2-e88e1/bin/iPhoneSimulator12.2-x86_64.sdk/build-openssl-1.1.0j.log
  Configure...
  Make (using 4 thread(s))...
Problem during make - Please check /Users/houyi/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.0j.2-e88e1/bin/iPhoneSimulator12.2-x86_64.sdk/build-openssl-1.1.0j.log
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5285k  100 5285k    0     0  38957      0  0:02:18  0:02:18 --:--:-- 39678

Excuse me, did anybody meet you? Thank you very much for what caused this and how to solve it.

**Comment by keeshux** [comment]
Have you actually checked the log?

**Comment by sundaleek** [comment]
@keeshux how to fix this error?)
