### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by ricain** [passepartoutvpn/passepartout-ios#93]
Hi,

[iOS 13](https://www.apple.com/ios/ios-13-preview/) beta is out for developers and it brings dark mode to iPhones. 

1. Can Passepartout app get a dark mode too?
2. Can it be automatically turn on and off depending on system wide dark mode?

If it could be done, it would be great :heart_eyes:

Thank

**Comment by keeshux** [comment]
Nothing about it before the official release.

**Comment by keeshux** [comment]
@ricain as you can see from the referencing commit, Dark Mode is ready but will only be enabled after iOS 13 is released.

**Comment by ricain** [comment]
thank :+1: 

Why wait for the stable release? If I am correct this code will work on ios 13 beta and will not impact ios 12 installs.
Plus you do not have to release a new version until official ios 13 release.

**Comment by DanielOaks** [comment]
I can't speak for keeshux but the commit above describes why the wait for stable release:

> Dark Mode cannot be enabled until iOS 13 release, because the App Store rejects binaries built with Beta SDKs.
>
> Uncomment when rebuilding with iOS 13 SDK.

**Comment by ricain** [comment]
This is why! thank :+1:
