### ISSUE TITLE
Updating server list from Mullvad provider is not working

### ISSUE THREAD

**Issue by xago9** [passepartoutvpn/passepartout-ios#96]
Hi,

Since 2 versions, I can't reload the server list using Mullvad provider, I was thinking that the new version (1.8.0) has fixed it but I was wrong. When I try to reload, it show a reload icon and then it disappear, the problem is that the update date don't change (it's still on august 2 since I updated the app) and the list is not refreshed (for example I don't have new servers that Mullvad added like Dubai and Albania). It was perfectly working before 1.7.0 and since then I can't reload anything. I tried to delete the provider, tried to restart the phone, delete and install the app again but nothing work. 

I'm on iOS 11.3.1 / iPhone 7 if it can help.

**Comment by keeshux** [comment]
It has nothing to do with the app. Thing is that the Mullvad infrastructure download is non-interactive and must be done manually (by me), so I will right away.

I know that the refresh button is unintuitive, because the action is only possible every 10 minutes. For now kill and reopen the app.

**Comment by keeshux** [comment]
Self-note, parse Mullvad servers from here: https://mullvad.net/en/servers/

**Comment by keeshux** [comment]
@xago9 refresh Mullvad now and you'll get the new servers.

**Comment by xago9** [comment]
Thanks for the quick update, but it seems that my problem still persist. When I try to refresh, nothing happens, the update time stamp don't change at all and server list remain the same. Is there anything else I can try to do to fix the problem ?

**Comment by xago9** [comment]
Here we go, I spotted the problem. I'm currently a french user of your app so I'm using the French translated app, I changed my phone language to english, came back to the app, refreshed and guess what ? Servers are here and timestamp is updated ! So something wrong is happening when the app is translated (in french at least). Hope it will help you for other users.
