### ISSUE TITLE
App availability in Russia

### ISSUE THREAD

**Issue by dankimio** [passepartoutvpn/passepartout-ios#97]
Is there a reason this app is not available in the Russian App Store?

**Comment by keeshux** [comment]
Sadly Apple bans VPN apps from Russia, China and a few other countries.

**Comment by dankimio** [comment]
@keeshux Any sources on that? Most VPNs are available in Russia, unlike China.

**Comment by keeshux** [comment]
IIRC I had apps rejected several times for ticking the Russian store, but I can certainly give it a new try.

**Comment by keeshux** [comment]
@dankimio let me know if the app becomes available in Russia in the next 24 hours. I can't assure it will stay available in case I'm prompted for removal by Apple. I'm genuinely unaware of any ToS the app could be breaking, but with the App Store you never know until it just happens.

**Comment by dankimio** [comment]
Showing up now!
